services:
  wordpress:
    image: wordpress:latest
    ports:
      - "8000:8000"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - wordpress_data:/var/www/html
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
